spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mariadb://localhost:3306/jmlim_test
    username: jmlim
    password: jmlim1234
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    jdbc-type-for-null: varchar
    cache-enabled: true
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: reuse
    default-statement-timeout: 6000
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.jmlim.upload.demo.mapper
  executor-type: reuse

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace